apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.37.1
appVersion: 4.26.0-20241101
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: 2.16.0
  name: keda
  condition: autoscaling.enabled, keda.enabled
- repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.3
  name: ingress-nginx
  condition: ingress.enableWithController, ingress-nginx.enabled
- repository: https://jaegertracing.github.io/helm-charts
  version: 3.3.2
  name: jaeger
  condition: tracing.enabled, jaeger.enabled
- repository: https://prometheus-community.github.io/helm-charts
  version: 65.8.1
  name: kube-prometheus-stack
  condition: monitoring.enabled, prometheus-stack.enabled
maintainers:
  - name: SeleniumHQ
    email: selenium-developers@googlegroups.com
    url: https://github.com/SeleniumHQ
sources:
  - https://github.com/SeleniumHQ/docker-selenium
