crossBrowsers:
  chromeNode:
    # Keep the first iteration with latest version of Chrome
    - nameOverride:
      hpa:
        browserVersion: ''
    - nameOverride: '{{ $.Release.Name }}-node-chrome-131'
      imageTag: '131.0'
      hpa:
        browserVersion: '131.0'
    - nameOverride: '{{ $.Release.Name }}-node-chrome-130'
      imageTag: '130.0'
      hpa:
        browserVersion: '130.0'
    - nameOverride: '{{ $.Release.Name }}-node-chrome-129'
      imageTag: '129.0'
      hpa:
        browserVersion: '129.0'
    - nameOverride: '{{ $.Release.Name }}-node-chrome-128'
      imageTag: '128.0'
      hpa:
        browserVersion: '128.0'
  firefoxNode:
    # Keep the first iteration with latest version of Firefox
    - nameOverride:
      hpa:
        browserVersion: ''
    - nameOverride: '{{ $.Release.Name }}-node-firefox-133'
      imageTag: '133.0'
      hpa:
        browserVersion: '133.0'
    - nameOverride: '{{ $.Release.Name }}-node-firefox-132'
      imageTag: '132.0'
      hpa:
        browserVersion: '132.0'
    - nameOverride: '{{ $.Release.Name }}-node-firefox-131'
      imageTag: '131.0'
      hpa:
        browserVersion: '131.0'
    - nameOverride: '{{ $.Release.Name }}-node-firefox-130'
      imageTag: '130.0'
      hpa:
        browserVersion: '130.0'
    - nameOverride: '{{ $.Release.Name }}-node-firefox-129'
      imageTag: '129.0'
      hpa:
        browserVersion: '129.0'
    - nameOverride: '{{ $.Release.Name }}-node-firefox-128'
      imageTag: '128.0'
      hpa:
        browserVersion: '128.0'
  edgeNode:
    # Keep the first iteration with latest version of Edge
    - nameOverride:
      hpa:
        browserVersion: ''
    - nameOverride: '{{ $.Release.Name }}-node-edge-131'
      imageTag: '131.0'
      hpa:
        browserVersion: '131.0'
    - nameOverride: '{{ $.Release.Name }}-node-edge-130'
      imageTag: '130.0'
      hpa:
        browserVersion: '130.0'
    - nameOverride: '{{ $.Release.Name }}-node-edge-129'
      imageTag: '129.0'
      hpa:
        browserVersion: '129.0'
    - nameOverride: '{{ $.Release.Name }}-node-edge-128'
      imageTag: '128.0'
      hpa:
        browserVersion: '128.0'
